---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: marcelocorreia/go-glide-builder
    tag: latest

inputs:
  - name: goglidebuilder

run:
  dir: goglidebuild
  path: ls
  args: [ -l ]

