---
platform: linux

image_resource:
  type: docker-image
  source:
    repository:  marcelocorreia/go-glide-builder

inputs:
  - name: go_glide_builder

outputs:
  - name: /tmp/

run:
  path: /bin/ls
  args: -l