---
platform: linux

image_resource:
  type: docker-image
  source:
    repository:  debian/jessie-slim

inputs:
  - name: go_glide_builder

outputs:
  - name: /tmp/

run:
  path: /bin/ls
  args: [ -l ]