---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: docker
    tag: latest

inputs:
  - name: goglidebuilder

run:
  dir: goglidebuilder
  path: uname
  args: [ -a ]

run:
  dir: goglidebuilder
  path: docker
  args: [ ps , -aq ]

